### ISSUE TITLE
help request: looking similar documents from a random list

### ISSUE THREAD

**Issue by zeroasterisk** [NaturalNode/natural#252]
Thank for this module -- **kudos** -- it looks excellent.

I’d like suggestions on approach, as I'm sure there's an elegant solution for this problem, and without guidance I will likely come up with kludge.

```
Given ~100 text documents of varying length (eg: email bodies)
When several of those text documents are significantly similar to each other
Then identify/extract them, and score their similarity.  
```

Basically, I want to find similar text blocks in a range, and alert if similar "enough”...  

Yes docs: A, B, and F could be similar to each other, while docs E, J, and Z are similar to each other... I plan on weighing this to really only care about *very* similar documents.

Anyone know of a good way to do that, better than my first brute force impulse: 
* tokenize/stem each doc, 
* compare each with the rest of the list, via *string distance*
 * very heavy approach, lots of recursion and indexing, N factorial territory.

Ideas, help, guidance, heckling, all appreciated!

**Comment by kkoch986** [comment]
can you elaborate on the kind of similarity you are looking for? using your approach of sting distance will really only help you if you want to compare the exact contents of the documents (i.e. is one document a verbatim copy of another) 

If you're trying to compare a more semantic similarity i would suggest starting with tokenize/stem as you said but then maybe compare the words as a bag of words instead of comparing the string distance of both documents. Since stemming will reduce the variability in the words (i.e. runner and running go down to run) you could count the number of stems the 2 documents have in common and get a sense for how similar they are.

That would be where i would start, maybe looking at WN and expanding the synonyms could help match even better but it would require a bit of experimentation.

Hope that helps! as with everything in nlp there are a lot of ways to attack the problem so just starting with anything and analyzing the results and trying to figure out what went right/wrong can be helpful in arriving at a working set up.
