### ISSUE TITLE
are to ar?

### ISSUE THREAD

**Issue by bingomanatee** [NaturalNode/natural#300]
the word 'are' is stemming to 'ar'; are there configs/ways to handle strange cases?

**Comment by jburb** [comment]
I think you can try instantiating your classifier with the other bundled
stemmer object (it uses porter stemmer by default).

You could always patch porter stemmer or fork your own version that
contains a blacklist of words not to stem then pass that in. I've been
considering this myself.

On Aug 8, 2016 1:33 PM, "Dave Edelhart" <notifications@github.com> wrote:

the word 'are' is stemming to 'ar'; are there configs/ways to handle
strange cases?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/NaturalNode/natural/issues/300>, or mute the thread

**Comment by bingomanatee** [comment]
thanks; I believe I am using porterStemmer

          return natural.PorterStemmer.stem(word.toLowerCase());

**Comment by jburb** [comment]
Np. I hope this enables you to do what you're looking to do!

**Comment by kkoch986** [comment]
seems like nltk has something to handle 'are':

```
>>> stemmer = PorterStemmer()
>>> stemmer.stem("are")
u'are'
```

pretty sure it must be something like what @jburb described because other implementations still seem to stem `are` to `ar`
