### ISSUE TITLE
BayesClassifier confidence precision

### ISSUE THREAD

**Issue by loretoparisi** [NaturalNode/natural#307]
I'm running a `BayesClassifier` on song lyrics to classify in two specific classes (explicit or not) manually labeled based on the lyrics text.
I have found that confidence values returned by `classifier.getClassifications` seems to have (what I presume) out of range values like:

```
 {
    "label": "explicit",
    "value": 1.1684298657209347e-125
  },
  {
    "label": "safe",
    "value": 6.187975801661305e-144
  }
]
```

Is that an error?

**Comment by jburb** [comment]
Hi Loreto,

These Bayesian numbers are always jarring if you don't expect them, but
they are most likely correct.

The results of Bayesian probability for text get very small because they
are essentially products of several probabilities. You can find more
details by looking around on stack overflow.

One thing you can do, if you are looking for a score that is easier on the
eyes and brain, is to take the ratio of the greater number to the smaller
number for each classification. That's not a professional opinion but it
has worked for me when presenting and eyeballing classification results.

Best of luck,
 - Josh

**Comment by loretoparisi** [comment]
@jburb yes it makes sense representing with the ration rather than the absolute value, it makes those number more human readable, thanks for the clarification!

**Comment by jburb** [comment]
No problem :)
