### ISSUE TITLE
Does tfidf support localization?

### ISSUE THREAD

**Issue by playground** [NaturalNode/natural#339]

**Comment by kkoch986** [comment]
unfortunately right now the tokenizer is hard-coded (see https://github.com/NaturalNode/natural/blob/master/lib/natural/tfidf/tfidf.js#L24-L25) shouldn't be too hard to refactor though.

we spoke awhile ago (cant seem to find the issue where this happened) about refactoring things so that one could set a global language and all the tools could automatically infer which algorithms to use. i dont think we ever really made any progress in that direction though
