### ISSUE TITLE
Question: How to train it with domain specific words? How to tokenize regular expn

### ISSUE THREAD

**Issue by rajaraodv** [NaturalNode/natural#352]
Sorry,
I don't know where else to ask. I am looking at wit.ai, api.ai and other services. They all seem to provide "intent" and "Entities" and allows us to specify domain specific words and synonyms. Wondering how to do that?
Also, I need to show auto-complete suggestions as the user types. So if the user is typing "Piz", I need to suggest "Pizza". How to do that?

**Comment by PauloQuerido** [comment]
Hi.

I'm not developing Natural but using it in my own projects. This said, I think domain specific training must be done "with" Natural, not "in" Natural.

You should consider training different datasets for different domains. Doing that, you get several classifiers, one for each domain.

This has been my aproach.

**Comment by kkoch986** [comment]
i think what @PauloQuerido is saying is probably the best approach. not sure the best way to guide you on autocomplete since there are a lot of ways to go about doing it. you may want to look into the [Trie](https://github.com/NaturalNode/natural/blob/master/lib/natural/trie/trie.js) it is a data structure which is extremely efficient at doing prefix searches on large sets of strings.
