### ISSUE TITLE
Issue with Simple Sentences

### ISSUE THREAD

**Issue by sachintah** [NaturalNode/natural#377]
I am expecting "fine" response from classifier, however getting default_response, please help as when i tried the same using dialogflow it gave me expected result

------------------------------------------------------------------------

var natural = require('natural')
var classifier = new natural.BayesClassifier();  

classifier.addDocument("default", "default_response")
classifier.addDocument("how are you?", "fine")

classifier.train(); 
console.log(classifier.classify('how are you?'))

------------------------------------------------------------------------

Regards
Sachin

**Comment by Samurais** [comment]
Come to the same issue.

**Comment by lula** [comment]
Hello guys!

I think the result are correct. I've been playing with Natural for some weeks, I'm not an expert. Just sharing my thoughts here about your issue. Hope this might help somehow.

When doc _how are you?_ is added with `classifier.addDocument("how are you?", "fine")` the classifier uses a default tokenizer and stemmer. Your classifier training docs are:

```
console.log(classifier.docs);

 [ { label: 'default_response', text: [ 'default' ] } ]
```

Words _how_, _are_ and _you_ are not taken into account as they are not nouns or something similar. I haven't checked the code yet to be more precise. The same defaults should be also applied to the text you want to classify!

Text _how are you?_ cannot be classified, therefore every category has the same probability to be chosen. A classifier is not a string matcher. If you categorized _are how you man?_ instead the document would have looked like:

```
classifier.addDocument('default', 'default_response');
classifier.addDocument('how are you man?', 'fine');
classifier.train();
console.log(classifier.docs);

[ { label: 'default_response', text: [ 'default' ] },
  { label: 'fine', text: [ 'man' ] } ]
```

With this training: 

```
console.log(classifier.classify('how are you?')); 
console.log(classifier.getClassifications('how are you?'))

default_response
[ { label: 'default_response', value: 0.6666666666666666 },
  { label: 'fine', value: 0.6666666666666666 } ]
```
```
console.log(classifier.classify('how are you man?')); 
console.log(classifier.getClassifications('how are you man?'))

fine
[ { label: 'fine', value: 0.6666666666666666 },
  { label: 'default_response', value: 0.3333333333333333 } ]
```

You can also use other Natural tokenizers and stemmers or write your own, rather than default ones. See more in the [docs](https://github.com/NaturalNode/natural#classifiers).

Cheers!

**Comment by Samurais** [comment]
Make sense, thank you.

**Comment by kkoch986** [comment]
@lula thanks for that response, what youre saying is totally correct. If you see here: https://github.com/NaturalNode/natural/blob/master/lib/natural/classifiers/classifier.js#L109-L110 we call tokenizeAndStem which will by default remove stopwords (see the list of stop words [here](https://github.com/NaturalNode/natural/blob/master/lib/natural/util/stopwords.js))

i havent tested this but im pretty sure if you set `classifier.keepStops = true` on your classifier instance then add the documents you will find they should be persisted.

hope that helps!
