### ISSUE TITLE
Error while natural = require('natural')

### ISSUE THREAD

**Issue by praveshbalhara** [NaturalNode/natural#430]
Hi

I am getting error while I require natural as below.
var natural = require('natural');

Error : 
TypeError: word.trim is not a function
    at loadDictionary (\node_modules\natural\lib\natural\stemm
ers\indonesian\stemmer_id.js:136:21)

In file stemmer_id.js
function loadDictionary(){
    var fs = require('fs');
    var dirname = __dirname + "/../../../../data/kata-dasar.txt";
    var fin = fs.readFileSync(dirname).toString().split("\n");
    for(var i in fin){
        var word = fin[i];
        **word = word.trim();**
        dictionary.push(word);
    }
}

error is => word = word.trim();
correction is =>
**if (typeof word !== 'string') {
    word = word .toString();
  }**

So that the function becomes

function loadDictionary(){
    var fs = require('fs');
    var dirname = __dirname + "/../../../../data/kata-dasar.txt";
    var fin = fs.readFileSync(dirname).toString().split("\n");
    for(var i in fin){
        var word = fin[i];
       if (typeof word !== 'string') {
          word = word .toString();
      }
        **word = word.trim();**
        dictionary.push(word);
    }
}

Similar issue in file prefix_rules.js at line number 36

**Comment by praveshbalhara** [comment]
I installed natural through npn install and then used natural as bellow. I have not cloned the code from github repo manually.
var natural = require('natural');

Pravesh

**Comment by Hugo-ter-Doest** [comment]
I installed natural from npm and did this:
```javascript
hugo@hugo-Z97-D3H:~/Workspace/test_natural_from_npm$ cat testNatural.js 
var natural = require('natural');
console.log('hello');
hugo@hugo-Z97-D3H:~/Workspace/test_natural_from_npm$ nodejs testNatural.js 
hello
hugo@hugo-Z97-D3H:~/Workspace/test_natural_from_npm$ nodejs -v
v9.11.1
hugo@hugo-Z97-D3H:~/Workspace/test_natural_from_npm$ 
```
What version is your nodejs?

Hugo

**Comment by Hugo-ter-Doest** [comment]
I'm sorry. I ran the version from NPM with node version v6.14.1 and could succesfully require natural. Could you give me more details about what you did exactly so I can reproduce? So a step-by-step description leading to the error you described. Thanks!

Hugo

**Comment by lminhang** [comment]
Hi @Hugo-ter-Doest , I'm having the same problem for prefix_rules.js. I recalled that I used to face this same error in stemmer_id.js in past versions, and the error has been patched for that file. 

So I managed to hack the error away by replicating the solution that patched stemmer_id.js in commit https://github.com/NaturalNode/natural/commit/0ce591f751e5b5b8839127977137e294eb06c770 on prefix_rules.js. I'm on node version v8.7.0.

**Comment by ashwinkodialbail** [comment]
<img width="1109" alt="screen shot 2018-05-03 at 10 56 09 pm" src="https://user-images.githubusercontent.com/25717886/39592706-386aa568-4f25-11e8-9d82-e3b8a74eb8d5.png">

**Comment by Hugo-ter-Doest** [comment]
It seems to be related to the use of for-in to loop through an array. If the array is out-of-the box, there is no problem, but if you extend the array's prototype, I get the same error as you have. That is why the use of for-in for array is considered bad-practice by some. The following sample illustrates what is going on:
```javascript
var natural = require('natural');

Array.prototype.someExtension = function() {};
var dictionary = [];
function loadDictionary() {
    var fs = require('fs');
    var dirname = "./node_modules/natural/data/kata-dasar.txt";
    var fin = fs.readFileSync(dirname).toString().split("\n");
    for(var i in fin){
      if (typeof fin[i] != "string") {
        console.log("Alarm, index + " + i + " is not a string: " + fin[i])
      }
      var word = fin[i];
      word = word.trim();
      dictionary.push(word);
    }
}

loadDictionary();
```
When I run this I get:
```javascript
Alarm, index someExtension is not a string: function () {}
/home/hugo/Workspace/testNpmNatural/testNatural.js:14
      word = word.trim();
                  ^

TypeError: word.trim is not a function
    at loadDictionary (/home/hugo/Workspace/testNpmNatural/testNatural.js:14:19)
    at Object.<anonymous> (/home/hugo/Workspace/testNpmNatural/testNatural.js:19:1)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Function.Module.runMain (module.js:690:10)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:666:3

![](https://user-images.githubusercontent.com/25717886/39592706-386aa568-4f25-11e8-9d82-e3b8a74eb8d5.png)
```  
So, I think your array's prototype is somewhere extended, and the for-in construct tries to process this element as a word. To repair this you have to replace the for-in constructs in `prefix_rules.js` and `stemmer_id.js` by a `forEach` or a simple `for (var i = 0; i < fin.length; i++)` construct.

I will repair the version here in Github, because the `prefix_rules.js` still uses the for-in construct.

Hugo

**Comment by Hugo-ter-Doest** [comment]
Repaired `prefix_rules.js` in commit https://github.com/NaturalNode/natural/commit/bee0421ed4f568bd7824fea882dcfd0995d8dd20

Hugo

**Comment by Hugo-ter-Doest** [comment]
Please comment if this did not fix your problem.

Hugo

**Comment by Hugo-ter-Doest** [comment]
I think you need to use browserify or webpack to convert the calls to the filesystem to something that can work in de browser.

**Comment by buildbreakdo** [comment]
Okay, the issue is the path being used in readFileSync here:

```
function loadDictionary(){
    var fs = require('fs');
    var dirname = __dirname + "/../../../../data/kata-dasar.txt";
    var fin = fs.readFileSync(dirname).toString().split("\n");
    fin.forEach(function (word) {
        if (word) {
          dictionary.push(word.trim());
        }
    });
}

```

While building with webpack if you `console.log` the path you get `//../../../../data/kata-dasar.txt` which fails to resolve. Webpack `__dirname` defaults to `/` unless configured otherwise. Can read about this issue in depth here: https://github.com/webpack/webpack/issues/1599.

After messing with this for a few hours, the fix went with was:

1. Convert `./data/kata-dasar.txt` to JSON.
2. Replace `loadDictionary` in `./lib/natural/stemmers/indonesian/prefix_rules.js` and `./lib/natural/stemmers/indonesian/stemmer_id.js` with:

```
function loadDictionary(){
    dictionary = dictionary.concat(require("./../../../../data/kata-dasar.json"));
}
```

As of node 0.5 there is a native loader for JSON. Might as well take advantage of that and not read file then split newlines over 30K lines, then trim each word (why are we trimming clean data?). Can take advantage of the native loader and JSON format to speed things up quite a bit. Napkin math benchmark tests showed a decrease in start time of about 600ms. This also makes the project work on docker -- presently read file sync (as is) is breaking in these environments like AWS SAM Local (aka AWS Lambda Emulator/Serverless).

**Comment by Hugo-ter-Doest** [comment]
Did some repairs to fix your issues with `kata-dasar.txt`:
* Removed line 19362 with `oper "v,"`
* Moved the file to `lib/natural/stemmers/indonesian/data`
* Converted it to JSON
* Made the stemmer work with the new JSON file in the new location

Will upload a new version to NPM soon.
