### ISSUE TITLE
Excessive load CPU

### ISSUE THREAD

**Issue by troyamtec** [NaturalNode/natural#471]
Hello guys, I'm getting a lot of CPU Load w/ natural.

1. Can you help me to understand how many times I need put the trainer?

2. I need to reload the trainer when received a new data?

**Comment by Hugo-ter-Doest** [comment]
Which trainer are you using? Brill's POS trainer, Bayesian, MaxEnt?

**Comment by rkeller1** [comment]
Abbrechen

Am 11.11.2018 1:06 nachm. schrieb "Hugo ter Doest" <notifications@github.com
>:

Which trainer are you using? Brill's POS trainer, Bayesian, MaxEnt?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/NaturalNode/natural/issues/471#issuecomment-437664757>,
or mute the thread

**Comment by troyamtec** [comment]
Thanks guys! I bought a new server with 24 CPU's and my problem was solved. Now we're using natural with face-api.js
