### ISSUE TITLE
SentenceTokenizer ignores last sentence if no punctuation at end

### ISSUE THREAD

**Issue by eloyer** [NaturalNode/natural#549]
Example: Using the SentenceTokenizer on the string 
`This is a sentence. But is this also one` 
returns 
`['This is a sentence.']`

**Comment by Hugo-ter-Doest** [comment]
Issue #552 about compatibility with Safari and issues #549 and #550 made me think about another direction for solving this. Also because I could hardly read and process the regular expression with lookbehinds and lookaheads. I though a more careful and elaborate solution based on parsing was needed. So I build a PEGJS grammar and generated a sentence parser. Pull request is here #558

**Comment by Hugo-ter-Doest** [comment]
Solved in #558
