### ISSUE TITLE
SentenceTokenizer omits the portion of a sentence preceding a quotation

### ISSUE THREAD

**Issue by eloyer** [NaturalNode/natural#550]
Using SentenceTokenizer on the string
`This is a sentence. And another where ‘Someone says something.’`
returns
`['This is a sentence.', '‘Someone says something.’']`

**Comment by Hugo-ter-Doest** [comment]
Issue #552 about compatibility with Safari and issues #549 and #550 made me think about another direction for solving this. Also because I could hardly read and process the regular expression with lookbehinds and lookaheads. I though a more careful and elaborate solution based on parsing was needed. So I build a PEGJS grammar and generated a sentence parser. Pull request is here #558

**Comment by Hugo-ter-Doest** [comment]
Your example is a bit problematic because the . and quote ' are in reverse order. So you are asking for some robustness wrt incorrect syntax. The output of the new parser-based solution would be:
````
[
   "This is a sentence.",
   "And another where ‘Someone says something.",
   "’"
]

**Comment by Hugo-ter-Doest** [comment]
This solved in the new grammar-based sentence tokenizer.
