### ISSUE TITLE
Save data in Mongodb

### ISSUE THREAD

**Issue by Kaen18** [NaturalNode/natural#681]
It is possible to save the trained data in a database, in this case Mongodb instead of saving it in a JSON file, so that the already trained data is not deleted every time I restart my serveIt is possible to save the trained data in a database, in this case Mongodb instead of saving it in a JSON file, so that the already trained data is not deleted every time I restart my serve

**Comment by khadeshyam** [comment]
how did you load the model can u provide some code snippets

**Comment by Hugo-ter-Doest** [comment]
Of course, we can build everything we want :-) 

I am curious to know which module you are working with? Is it the Bayesian classifier?

I think this would be a configuration to choose between database and JSON. In the end a back-end to save to and load from different types of storage methods. But starting with a choice between JSON and database would be great.

**Comment by khadeshyam** [comment]
Yeah it's Bayesian classifier module

**Comment by Hugo-ter-Doest** [comment]
Some design ideas:
- pass Classifier in classifier.js a config object. Also put the stemmer in there to prevent many arguments when creating the object.
- adapt the load and and save methods to work with mongodb depending on the configuration: return a key on save, and load using a key. Instead of filenames.

**Comment by khadeshyam** [comment]
can anyone provide code snippets of Bayesian classifier module that's compatible with the latest package version

**Comment by Hugo-ter-Doest** [comment]
You could take a look at the tests:
`https://github.com/NaturalNode/natural/blob/master/spec/bayes_classifier_spec.js`

**Comment by fernandovargascabrera** [comment]
This will be amazing! The classifier could receive an object that implements an interface, allowing us to access the data and handle it effectively. This enables the user implementing 'natural' to choose their preferred database. Instead of loading all the data at once, we could simply read from the database.

**Comment by Hugo-ter-Doest** [comment]
Yes, you could store a trained classifier in a database. Later on you could retrieve and re-instate it as an object using `SetPrototypeOf``. 

Wrt design I am considering a backend that supports file-based storage and MongoDB to begin with by means of plugins or something like that. In this way we can abstract away the concrete storage method.

**Comment by Hugo-ter-Doest** [comment]
See #727

**Comment by Hugo-ter-Doest** [comment]
Support for a number of storage methods has been added. See #727
