### ISSUE TITLE
Missing typings for LevenshteinDistanceSearch as well as for DamerauLevenshteinDistanceSearch

### ISSUE THREAD

**Issue by d521bb85** [NaturalNode/natural#686]
Hi,

Just found that I cannot use `LevenshteinDistanceSearch` neither `DamerauLevenshteinDistanceSearch` with TypeScript because of lack of typings. Following the given type for `LevenshteinDistance`, it's possible to pass `search` property, however `LevenshteinDistance` method explicitly defines it as `false`.

```js
function LevenshteinDistance (source, target, options) {
  const levOptions = _.extend({}, options || {}, { damerau: false, search: false })
  return levenshteinDistance(source, target, levOptions)
}
```

**Comment by Hugo-ter-Doest** [comment]
Well, not exactly: there is a separate `LevenshteinDistanceSearch` function that has the `search` property set to `true`:

```
function LevenshteinDistanceSearch (source, target, options) {
  const levOptions = _.extend({}, options || {}, { damerau: false, search: true })
  return levenshteinDistance(source, target, levOptions)
}
```

**Comment by obedparla** [comment]
This issue shouldn't have been closed. It's not currently possible to use `LevenshteinDistanceSearch` due to the issue @d521bb85 mentioned.

Trying to pass `{search: true}` to `LevenshteinDistance` won't work since that argument will be ignored (as it's overridden within the `LevenshteinDistance` function).

The fix is to update the types to export both `_Search` functions.
