### ISSUE TITLE
CPU Usage?

### ISSUE THREAD

**Issue by wayne-wang-1119** [NaturalNode/natural#747]
**Is your feature request related to a problem? Please describe.**
I want to see if we can add some info for cpu usage for using the semantic to predict semantic score
**Describe the solution you'd like**
a report / benchmark
**Describe alternatives you've considered**
other packages but natural is super powerful and i want to use it on cloud
**Additional context**

**Comment by Hugo-ter-Doest** [comment]
> I want to see if we can add some info for cpu usage for using the semantic to predict semantic score
Which module or functionality do you mean?

**Comment by wayne-wang-1119** [comment]
I am using Sentiment Analyzer

**Comment by wayne-wang-1119** [comment]
Hi Hugo,

Just want to reach out again to see if there's any answers on this. Natural is a great package I want to make sure I understand its bandwidth so it does not explode my prod on GCP.

**Comment by Hugo-ter-Doest** [comment]
Well, I do not want to integrate profiling support into natural at the moment.

On the other hand: the sentiment analyzer has a linear time complexity in terms of the length the sentence being analysed:
```
words.forEach((token) => {
  // calculate sentiment
})
```
So, you don't have to worry about the CPU load. The size of the lexicon may be however, because it is in memory. You can monitor that with node itself or additional tools.
